---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: grafana
  annotations:
    environment: {{ .ENV }}
    {{ if eq .ENV "notprod" }}downscaler/uptime: Mon-Fri 07:00-18:30 Europe/London{{ end }}
spec:
  replicas: 1
  selector:
    matchLabels:
      name: grafana
  revisionHistoryLimit: 3
  template:
    metadata:
      labels:
        name: grafana
    spec:
      securityContext:
        runAsUser: 1000
        fsGroup: 1000
      containers:
      - name: grafana
        image: quay.io/ukhomeofficedigital/dq-grfana-docker:{{ .DRONE_COMMIT_SHA }}
        imagePullPolicy: Always
        securityContext:
          runAsNonRoot: true
        resources:
          limits:
            cpu: 2
            memory: 3.2Gi
          requests:
            cpu: 1.5
            memory: 2Gi
        env:
          - name: SERVER_PORT
            value: '3000'
          - name: SERVER_PROXY_NAME
            value: {{ .HOSTNAME }}
          - name: SERVER_PROXY_PORT
            value: '443'
          - name: SERVER_REDIRECT_PORT
            value: '10443'
          - name: GF_AWS_PROFILES
            value: {{ .GF_AWS_PROFILES }}
          - name: GF_AWS_NOTPROD_REGION
            value: {{ .GF_AWS_NOTPROD_REGION }}
          - name: GF_AWS_PROD_REGION
            value: {{ .GF_AWS_PROD_REGION }}
          - name: GF_AWS_NOTPROD_ACCESS_KEY_ID
            value: {{ .GF_AWS_NOTPROD_ACCESS_KEY_ID }}
          - name: GF_AWS_NOTPROD_SECRET_ACCESS_KEY
            value: {{ .GF_AWS_NOTPROD_SECRET_ACCESS_KEY }}
          - name: GF_AWS_PROD_ACCESS_KEY_ID
            value: {{ .GF_AWS_PROD_ACCESS_KEY_ID }}
          - name: GF_AWS_PROD_SECRET_ACCESS_KEY
            value: {{ .GF_AWS_PROD_SECRET_ACCESS_KEY }}
        ports:
          - containerPort: 3000
        volumeMounts:
          - mountPath: /var/lib/grafana
            name: grafana

      - name: proxy
        image: quay.io/ukhomeofficedigital/dq-nginx-proxy-redirect:b58
        securityContext:
          runAsNonRoot: true
        env:
          - name: PROXY_SERVICE_HOST
            value: 'http://127.0.0.1'
          - name: PROXY_SERVICE_PORT
            value: '3000'
          - name: LOG_FORMAT_NAME
            value: 'json'
          - name: NAXSI_USE_DEFAULT_RULES
            value: 'FALSE'
          - name: CLIENT_MAX_BODY_SIZE
            value: '10'
        ports:
          - name: https
            containerPort: 10443

      volumes:
        - name: grafana
          persistentVolumeClaim:
            claimName: grafana
