---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: jira
  annotations:
    environment: {{ .ENV }}
    {{ if eq .ENV "notprod" }}downscaler/uptime: Mon-Fri 07:00-18:30 Europe/London{{ end }}
spec:
  replicas: 1
  selector:
    matchLabels:
      name: grafana
  revisionHistoryLimit: 3
  template:
    metadata:
      labels:
        name: grafana
    spec:
      securityContext:
        runAsUser: 1000
        fsGroup: 1000
      containers:
      - name: grafana
        image: quay.io/ukhomeofficedigital/jira-docker:{{ .DRONE_COMMIT_SHA }}
        imagePullPolicy: Always
        securityContext:
          runAsNonRoot: true
        resources:
          limits:
            cpu: 2
            memory: 3.2Gi
          requests:
            cpu: 1.5
            memory: 2Gi
        env:
          - name: SERVER_PORT
            value: '8080'
          - name: SERVER_PROXY_NAME
            value: {{ .HOSTNAME }}
          - name: SERVER_PROXY_PORT
            value: '443'
          - name: SERVER_REDIRECT_PORT
            value: '10443'
        volumeMounts:
          - mountPath: /var/atlassian/jira
            name: jira

      - name: proxy
        image: quay.io/ukhomeofficedigital/dq-nginx-proxy-redirect:b54
        securityContext:
          runAsNonRoot: true
        env:
          - name: PROXY_SERVICE_HOST
            value: 'http://127.0.0.1'
          - name: PROXY_SERVICE_PORT
            value: '8080'
          - name: LOG_FORMAT_NAME
            value: 'json'
          - name: NAXSI_USE_DEFAULT_RULES
            value: 'FALSE'
          - name: CLIENT_MAX_BODY_SIZE
            value: '100'
        ports:
          - name: https
            containerPort: 10443
      # - name: opensslsidekick
      #   image: quay.io/ukhomeofficedigital/dq-haproxy-openssl-sidekick:master
      #   imagePullPolicy: Always
      #   securityContext:
      #     runAsNonRoot: true
      #     runAsUser: 1000
      #   env:
      #     - name: HOST
      #       value: '10.3.0.11'
      #     - name: PORT
      #       value: '5431'
      #   ports:
      #      - containerPort: 5000
      volumes:
        - name: grafana
          persistentVolumeClaim:
            claimName: grafana
