apiVersion: networking.k8s.io/v1
kind: NetworkPolicy
metadata:
  name: allow-grafana
spec:
  podSelector:
    matchLabels:
      name: grafana
  ingress:
    - ports:
      - protocol: TCP
        port: 10443
