---
apiVersion: v1
kind: Service
metadata:
  labels:
    name: grafana-service
  name: grafana-service
spec:
  ports:
  - name: https
    port: 443
    targetPort: https
  selector:
    name: grafana
